version: 0.2

env:
   variables:
     PROJECT: Awsnewsolution
     DOTNET_CORE_RUNTIME : 6.0

phases: 
    install:
        runtime-versions:
            dotnet: ${DOTNET_CORE_RUNTIME}
        
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
            - dotnet restore
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
            - dotnet build -c Release
            - dotnet test -c Release
           
    post_build:
        commands:
            - echo "we are in the post build phase"
            - dotnet publish -c Release
            
